// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
declare const MAIN_WINDOW_VITE_NAME: string;

interface Device {
  id: string;
  name: string;
}

interface DeviceControl {
  scan: () => Promise<Device[]>;
  connect: (deviceId: string) => Promise<boolean>;
  disconnect: () => Promise<boolean>;
  getStatus: () => Promise<boolean>;
  type: (text: string) => Promise<boolean>;
  onStatusChange: (callback: (status: boolean) => void) => void;
  onTypingToggle: (callback: (enabled: boolean) => void) => void;
}

// Preload types
interface ThemeModeContext {
  toggle: () => Promise<boolean>;
  dark: () => Promise<void>;
  light: () => Promise<void>;
  system: () => Promise<boolean>;
  current: () => Promise<"dark" | "light" | "system">;
}

interface ElectronWindow {
  minimize: () => Promise<void>;
  maximize: () => Promise<void>;
  close: () => Promise<void>;
}

declare interface Window {
  themeMode: ThemeModeContext;
  electronWindow: ElectronWindow;
  deviceControl: DeviceControl;
}
